#基础镜像
FROM alpine:3.12

#环境变量
ENV TZ "Asia/Shanghai"

# conf
COPY conf/* /etc/fdfs/
COPY fastdfs.sh /home/

RUN set -x \
    && apk update \
    && apk add --no-cache --virtual .build-deps alpine-sdk build-base perl-dev openssl-dev pcre-dev zlib-dev git \
    && mkdir -p /usr/local/src \
    && cd /usr/local/src \
    && git clone https://github.com/happyfish100/libfastcommon.git --depth 1 \
    && git clone -b V6.08 https://github.com/happyfish100/fastdfs.git --depth 1    \
    && git clone https://github.com/happyfish100/fastdfs-nginx-module.git --depth 1  \
    && wget http://nginx.org/download/nginx-1.20.1.tar.gz \
    && tar -zxvf nginx-1.20.1.tar.gz \
    && cd /usr/local/src/libfastcommon \
    && ./make.sh \
    && ./make.sh install \
    && cd /usr/local/src/fastdfs/ \
    && ./make.sh \
    && ./make.sh install \
    && cd /usr/local/src/nginx-1.20.1/ \
    && ./configure --add-module=/usr/local/src/fastdfs-nginx-module/src/ \
    && make && make install \
    && apk del .build-deps \
    && apk add --no-cache pcre-dev bash curl tzdata \
    && mkdir -p /home/dfs \
    && chmod +x /home/fastdfs.sh

RUN cp /usr/local/src/fastdfs/init.d/fdfs_trackerd /etc/init.d/fdfs_trackerd \
    && cp /usr/local/src/fastdfs/init.d/fdfs_storaged /etc/init.d/fdfs_storaged \
    && rm -rf /usr/local/src*

VOLUME /home/dfs

EXPOSE 22122 23000 80

CMD ["/home/fastdfs.sh"]
